### ISSUE TITLE
openjdk image is deprecated

### ISSUE THREAD

**Issue by chrisl8** [rtuszik/photon-docker#1]
https://github.com/rtuszik/photon-docker/blob/e26c5c9e1096a1f0db0b5e098aa65771d14eb445/Dockerfile#L1

According to https://hub.docker.com/_/openjdk/ this image is deprecated and going away.

I'm not sure what the best alternative is. I'm using `FROM adoptopenjdk/openjdk11` personally.

**Comment by rtuszik** [comment]
Thanks. I have updated the Dockerfile!
