### ISSUE TITLE
Synology Nas Docker

### ISSUE THREAD

**Issue by Tazmanian79** [rtuszik/photon-docker#11]
Does somebody know how or can help to install this on a Synology NAS using Container Manager or Portainer?

**Comment by rtuszik** [comment]
Hi there,
I don't have a ton of experience with Synology, as I moved away from that platform a while ago, but I do have my instance running on Portainer. If you describe your issue, someone might be able to help.

**Comment by Tazmanian79** [comment]
I don't really have an issue (yet).  I did not try to install it.  But would be great is someone can explain the steps and what I should change.  Like I want to have the files in /volume1/docker/photon/

I also use Dawarich and this is the compose.yml that made it work ;-)
I didn't had to change much, only on the bottom the volumes:

`
version: '3'
networks:
  dawarich:
services:
  dawarich_redis:
    image: redis:7.0-alpine
    container_name: dawarich_redis
    command: redis-server
    restart: unless-stopped
    networks:
      - dawarich
    volumes:
      - shared_data:/var/shared/redis

  dawarich_db:
    image: postgres:14.2-alpine
    container_name: dawarich_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - dawarich

  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    depends_on:
      - dawarich_db
      - dawarich_redis
    volumes:
      - gem_cache:/usr/local/bundle/gems
      - public:/var/app/public
      - watched:/var/app/tmp/imports/watched
    networks:
      - dawarich
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['bin/dev']
    restart: unless-stopped
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOSTS: localhost
      TIME_ZONE: Europe/Brussels
      APPLICATION_PROTOCOL: http
      REVERSE_GEOCODING_ENABLED: true
      DISTANCE_UNIT: km
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - gem_cache:/usr/local/bundle/gems
      - public:/var/app/public
      - watched:/var/app/tmp/imports/watched
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['sidekiq']
    restart: unless-stopped
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      APPLICATION_HOSTS: localhost
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      RAILS_MAX_THREADS: 15
      APPLICATION_PROTOCOL: http
      REVERSE_GEOCODING_ENABLED: true
      DISTANCE_UNIT: km
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - dawarich_db
      - dawarich_redis
      - dawarich_app

volumes:
  db_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /volume1/docker/dawarich/db_data
      o: bind
  gem_cache:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /volume1/docker/dawarich/gem_cache
      o: bind
  shared_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /volume1/docker/dawarich/shared_data
      o: bind
  public:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /volume1/docker/dawarich/public
      o: bind
  watched:
    driver: local # Define the driver and options under the volume name
    driver_opts:
       type: none
       device: /volume1/docker/dawarich/watched
       o: bind
`

**Comment by rtuszik** [comment]
It will probably not be all that different for photon. 
Probably something like this:

```yaml
version: '3.7'

services:
  photon:
    image: rtuszik/photon-docker:latest
    volumes:
      - photon_data:/photon/photon_data
    restart: unless-stopped
    ports:
      - "2322:2322"

volumes:
  photon_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/docker/photon/
```

Give it a go and check the container logs. Download should start straight away. 

Please note, that you will also need to make the container accessible via HTTPS.

**Comment by Tazmanian79** [comment]
I'll give it a try in a few hours .
HTTPS is no prob.

I see there's also a docker-compose.build.yaml
I don't need that ?  Just run docker-compose.yml is enough?

**Comment by rtuszik** [comment]
Correct, the docker-compose.build.yaml can be used instead of the docker-compose.yml if you wanted to build it yourself instead of pulling my prebuilt image.

**Comment by Tazmanian79** [comment]
So I have to choose one.  Can you Tell me thé difference between thé 2 options ?

**Comment by rtuszik** [comment]
I would advise you to use the docker-compose.yml, as this will pull the image that is pre-built and verified to work from the container registry. This is the default way of installing this image. 

The build version is included for transparency and for people that have specific requirements. It's what I use in the testing environment.

**Comment by Tazmanian79** [comment]
It's installed.  now downloading the search index.  will take a while.
It's not yet accessable at port 2322 but think that will come after the search index will be downloaded.

**Comment by rtuszik** [comment]
Yes, photon will start once the index is downloaded and extracted. Feel free to reopen if you encounter any issues.

**Comment by Tazmanian79** [comment]
Everything is installed and Photon is running.
But how can I check if it's working?  If I go to http://localhost:2322/ I see this message
![Schermafbeelding 2024-10-09 084220](https://github.com/user-attachments/assets/2bc8c4b8-97d2-47cc-9f04-8e5ac2951ebe)

When I go to http://localhost:2322/api?q=Harare I have this
![Schermafbeelding 2024-10-09 084403](https://github.com/user-attachments/assets/10184a53-157c-417b-a1bb-3336050c06c9)


So I think it is working.
But how can I fine the API for Dawarich?
Is it just https://localhost:2322/Api?q=

**Comment by rtuszik** [comment]
For future clarification, for anyone else having the same question - Yes, the output shows that it is in fact working. 
As of now - photon needs to be exposed to Dawarich using https, which means that you will have to find a way to create a valid certificate. This can be done by way of a reverse proxy, Tailscale, cloudflare tunnels or similar.
