### ISSUE TITLE
feature: multiple countries

### ISSUE THREAD

**Issue by brvn0** [rtuszik/photon-docker#17]
Hello, I tried modifying the start script but there seems to be no easy way to index multiple but not all countries. I would be very happy if you'd supply me with either resources on how to achieve that goal or build a new release with that as a feature
Regards :)

**Comment by rtuszik** [comment]
I would love to implement this, and have spent quite some time trying to figure out how to, but unfortunately this is quite complicated. 

This Docker image works by importing the search indices provided in the [official Photon repo](https://github.com/komoot/photon). 

It’s not possible to merge these without spinning up multiple instances of Elasticsearch, merging them, and then creating a new dump, which is a resource-intensive and fairly complicated task and would have to be done locally by the user for their specific selection of countries. 

The only other way to achieve what you want to do is running your own Nominatim database, which on its own will be much larger than the full Photon index. 

The pipeline that is used to create the Photon indices is not public either (or at least I haven't been able to find it), so for now I haven't been able to find a good option for this. 

If you have any ideas, let me know. I'd be happy to implement something.
